### ISSUE TITLE
Ubuntu 14.04 LTS Instructions

### ISSUE THREAD

**Issue by SnakeO** [mc-jesus/FaceSwap#11]
I'll be leaving instructions here as I figure them out.

STEP 1 -- install gcc++ 4.9 (14.04LTS has 4.8 only)
Instructions via: https://askubuntu.com/questions/428198/getting-installing-gcc-g-4-9-on-ubuntu
`sudo add-apt-repository ppa:ubuntu-toolchain-r/test`
`sudo apt-get update`
`sudo apt-get install g++-4.9`

STEP 2 -- download dlib
While you are inside `Faceswap-master` directory:
`wget http://dlib.net/files/dlib-19.4.tar.bz2`
`tar xvjf dlib-19.4.tar.bz2`

STEP 3 -- install opencv
`apt-get install libopencv-dev python-opencv`

STEP 4 -- compile
cd into the source dir, and run `g++-4.9 -std=c++14 -o faceswapper *.cpp 'pkg-config opencv --cflags --libs' -Idlib-19.4 dlib-19.4/dlib/all/source.cpp -lpthread -lX11` (IMPORTANT NOTE: the single quote marks around `pkg-config opencv --cflags --libs` should be BACKTICKS but the code editor won't allow me to put backticks inside backticks) 

STEP 5 -- run
`./faceswapper`

If you get this error: `libdc1394 error: Failed to initialize libdc1394` then run this command:
`ln /dev/null /dev/raw1394`

**Comment by hrastnik** [comment]
There's more instructions in the README now

**Comment by SnakeO** [comment]
The instructions don't cover linux command-line.
