### ISSUE TITLE
swap face in real time on the desktop?

### ISSUE THREAD

**Issue by luckhhn** [mc-jesus/FaceSwap#21]
Thank you for your excellent work. Can you swap face in real time on the desktop?look forward to your reply

**Comment by hrastnik** [comment]
Yes. It does work in real time on desktop.

**Comment by luckhhn** [comment]
thanks  for your heart reply!
 my environment is vs2017, win10, opencv4.0.1, dlib19.17
I configured according to your instructions, but the following error occurred：
错误	LNK2001	无法解析的外部符号 USER_ERROR__inconsistent_build_configuration__see_dlib_faq_1	install_dlib

错误	LNK2001	无法解析的外部符号 USER_ERROR__inconsistent_build_configuration__see_dlib_faq_2	install_dlib
can you help me？
