### ISSUE TITLE
Possible division by zero

### ISSUE THREAD

**Issue by ghost** [mc-jesus/FaceSwap#6]
Hi,
thanks for sharing this nice face swapping example!
Looking through the code I spotted a little bug in the "Normalize CDF" for-loop in FaceSwapper.cpp:261-267. I think you meant to test [255] for zero instead of [i] in these lines.

Regards,
matthias

**Comment by hrastnik** [comment]
You're absolutely right!

EDIT: Should be fixed now. Thank you again for the input.
