### ISSUE TITLE
Cannot build source

### ISSUE THREAD

**Issue by jodusan** [mc-jesus/FaceSwap#8]
I am having the following problem:

`DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
 #error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
  ^
/usr/include/dlib/gui_core/gui_core_kernel_2.h:12:2: error: #error "Also make sure you have libx11-dev installed on your system"
 #error "Also make sure you have libx11-dev installed on your system"
`

How can I turn off DLIB_NO_GUI_SUPPORT ?
Libx11-dev is already installed.

**Comment by hrastnik** [comment]
You don't need GUI support to run the example. If you want to enable GUI support you should use cmake to build dlib, and disable DLIB_NO_GUI_SUPPORT from cmake.

**Comment by SnakeO** [comment]
@dulex123 what command did you use to compile the program?

**Comment by jodusan** [comment]
@SnakeO Can't remember :D
